# Generated by Django 5.2 on 2025-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
